import "./assets/globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@/context/ThemeContext";
import ThemeWrapper from "@/app/portfolio/components/ThemeWrapper";
import ScrollLockProvider from "@/providers/ScrollLockProvider";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ScrollLockProvider>
        <ThemeProvider>
          <ThemeWrapper>
            <ReactQueryProvider>
              <Toaster richColors />
              {children}
            </ReactQueryProvider>
          </ThemeWrapper>
        </ThemeProvider>
      </ScrollLockProvider>
    </html>
  );
}
