import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div className="absolute w-full bg-indigo-400 min-h-75 -z-1"></div>
      <Sidebar className="fixed top-0 left-0" />

      <div className="grid grid-rows-[70px_1fr] ml-[270px] min-h-screen">
        <Navbar className="h-full" />
        <div className="m-2 p-4">{children}</div>
      </div>
    </div>
  );
}
